const { faker } = require("@faker-js/faker");
const sequelize = require("../index");
const Product = require("../models/Product");
const Restaurant = require("../models/Restaurant");

const seedProducts = async () => {
  try {
    await sequelize.sync(); // Ensure tables are synced

    const restaurants = await Restaurant.findAll();
    if (restaurants.length === 0) {
      console.log(
        "No restaurants found. Add restaurants before seeding products."
      );
      return;
    }

    const category = ["Drink", "Meal", "Supplement"];

    const dataSet = [
      //Kemi bee cafe 2
      {
        name: "White Rice with Stew",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of rice, stew ",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://img-global.cpcdn.com/recipes/b9a21d2844ba2ce2/1200x230cq20/photo.jpg",
      },
      {
        name: "Jollof Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Jollof Rice",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://allnigerianfoods.com/wp-content/uploads/jollof_rice_recipe1-500x500.jpg",
      },
      {
        name: "Fried Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Fried rice",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://nkechiajaeroh.com/wp-content/uploads/2020/12/Nigerian-fried-rice-recipe-main-photo-3.jpg",
      },
      {
        name: "Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "one spoon of Rice",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/02/23/0/FNK_Perfect-Long-Grain-White-Rice-H_s4x3.jpg.rend.hgtvcom.1280.920.suffix/1592939598228.webp",
      },
      {
        name: "Beans",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One spoon",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.ohmyveg.co.uk/wp-content/uploads/2024/10/masala-beans-2-220x540.jpg",
      },
      {
        name: "Spaghetti",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://stinkingood.com/wp-content/uploads/2022/01/iStock-128202421-scaled.jpg",
      },
      {
        name: "Indomie Noodles",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://sisijemimah.com/wp-content/uploads/2019/05/indomie-noodles-stir-fry-21-1024x238.jpg",
      },
      {
        name: "MoinMoin",
        price: 200,
        category: category[2],
        rating: 5,
        description: "One Tasteful Moi-Moi",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.seriouseats.com/thmb/FyrplS03gmSGkFlRtc5WuqMp5YY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230111-Moin-Moin-Maureen-Celestine-hero-5c252cbc3b284be1b1f29414f2bdc29c.JPG",
      },
      {
        name: "Amale",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Amale",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://yummieliciouz.com/wp-content/uploads/2023/04/easy-amala-recipe.jpg",
      },
      {
        name: "Eba",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Eba",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2015/03/how-to-make-eba-food-nigerian-eba-img2-1.jpg",
      },
      {
        name: "FuFu",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful FuFu",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://kosherworldkitchen.com/wp-content/uploads/2024/12/Ghana-pounded-yam-fufu-scaled.jpg",
      },
      {
        name: "Meat",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Meat",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2020/02/boiled-meat-img-11-500x500.jpg",
      },
      {
        name: "Egg",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Egg",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://thumbs.dreamstime.com/b/hard-boiled-eggs-bowl-one-cut-25114925.jpg",
      },
      {
        name: "Fish",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Fish",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://static.vecteezy.com/system/resources/previews/050/392/528/non_2x/grilled-fish-with-lemon-and-herbs-on-white-background-photo.jpeg",
      },
      {
        name: "Plantain",
        price: 50,
        category: category[2],
        rating: 5,
        description: "One Tasteful Plan",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image:
          "https://flavortheglobe.com/wp-content/uploads/2021/12/Peruvian-oven-baked-plantains-recipe.jpg",
      },
      {
        name: "Pepsi",
        price: 350,
        category: category[0],
        rating: 4.3,
        description: "Chilled Pepsi drink",
        restaurantId: 2,
        isAvailable: "true",
        stock: 100,
        image: "https://m.media-amazon.com/images/I/51pGxfs4w1L.jpg",
      },

      //Divine Cafe (Oungbona) 3
      {
        name: "White Rice with Stew",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of rice, stew ",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://img-global.cpcdn.com/recipes/b9a21d2844ba2ce2/1200x230cq20/photo.jpg",
      },
      {
        name: "Jollof Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Jollof Rice",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://allnigerianfoods.com/wp-content/uploads/jollof_rice_recipe1-500x500.jpg",
      },
      {
        name: "Fried Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Fried rice",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://nkechiajaeroh.com/wp-content/uploads/2020/12/Nigerian-fried-rice-recipe-main-photo-3.jpg",
      },
      {
        name: "Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "one spoon of Rice",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/02/23/0/FNK_Perfect-Long-Grain-White-Rice-H_s4x3.jpg.rend.hgtvcom.1280.920.suffix/1592939598228.webp",
      },
      {
        name: "Beans",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One spoon",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.ohmyveg.co.uk/wp-content/uploads/2024/10/masala-beans-2-220x540.jpg",
      },
      {
        name: "Spaghetti",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://stinkingood.com/wp-content/uploads/2022/01/iStock-128202421-scaled.jpg",
      },
      {
        name: "Indomie Noodles",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://sisijemimah.com/wp-content/uploads/2019/05/indomie-noodles-stir-fry-21-1024x238.jpg",
      },
      {
        name: "MoinMoin",
        price: 200,
        category: category[2],
        rating: 5,
        description: "One Tasteful Moi-Moi",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.seriouseats.com/thmb/FyrplS03gmSGkFlRtc5WuqMp5YY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230111-Moin-Moin-Maureen-Celestine-hero-5c252cbc3b284be1b1f29414f2bdc29c.JPG",
      },
      {
        name: "Amale",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Amale",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://yummieliciouz.com/wp-content/uploads/2023/04/easy-amala-recipe.jpg",
      },
      {
        name: "Eba",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Eba",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2015/03/how-to-make-eba-food-nigerian-eba-img2-1.jpg",
      },
      {
        name: "FuFu",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful FuFu",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://kosherworldkitchen.com/wp-content/uploads/2024/12/Ghana-pounded-yam-fufu-scaled.jpg",
      },
      {
        name: "Meat",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Meat",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2020/02/boiled-meat-img-11-500x500.jpg",
      },
      {
        name: "Egg",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Egg",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://thumbs.dreamstime.com/b/hard-boiled-eggs-bowl-one-cut-25114925.jpg",
      },
      {
        name: "Fish",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Fish",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://static.vecteezy.com/system/resources/previews/050/392/528/non_2x/grilled-fish-with-lemon-and-herbs-on-white-background-photo.jpeg",
      },
      {
        name: "Plantain",
        price: 50,
        category: category[2],
        rating: 5,
        description: "One Tasteful Plan",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image:
          "https://flavortheglobe.com/wp-content/uploads/2021/12/Peruvian-oven-baked-plantains-recipe.jpg",
      },
      {
        name: "Pepsi",
        price: 350,
        category: category[0],
        rating: 4.3,
        description: "Chilled Pepsi drink",
        restaurantId: 3,
        isAvailable: "true",
        stock: 100,
        image: "https://m.media-amazon.com/images/I/51pGxfs4w1L.jpg",
      },

      //Y2K Cafe 4
      {
        name: "White Rice with Stew",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of rice, stew ",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://img-global.cpcdn.com/recipes/b9a21d2844ba2ce2/1200x230cq20/photo.jpg",
      },
      {
        name: "Jollof Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Jollof Rice",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://allnigerianfoods.com/wp-content/uploads/jollof_rice_recipe1-500x500.jpg",
      },
      {
        name: "Fried Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Fried rice",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://nkechiajaeroh.com/wp-content/uploads/2020/12/Nigerian-fried-rice-recipe-main-photo-3.jpg",
      },
      {
        name: "Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "one spoon of Rice",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/02/23/0/FNK_Perfect-Long-Grain-White-Rice-H_s4x3.jpg.rend.hgtvcom.1280.920.suffix/1592939598228.webp",
      },
      {
        name: "Beans",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One spoon",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.ohmyveg.co.uk/wp-content/uploads/2024/10/masala-beans-2-220x540.jpg",
      },
      {
        name: "Spaghetti",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://stinkingood.com/wp-content/uploads/2022/01/iStock-128202421-scaled.jpg",
      },
      {
        name: "Indomie Noodles",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://sisijemimah.com/wp-content/uploads/2019/05/indomie-noodles-stir-fry-21-1024x238.jpg",
      },
      {
        name: "MoinMoin",
        price: 200,
        category: category[2],
        rating: 5,
        description: "One Tasteful Moi-Moi",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.seriouseats.com/thmb/FyrplS03gmSGkFlRtc5WuqMp5YY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230111-Moin-Moin-Maureen-Celestine-hero-5c252cbc3b284be1b1f29414f2bdc29c.JPG",
      },
      {
        name: "Amale",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Amale",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://yummieliciouz.com/wp-content/uploads/2023/04/easy-amala-recipe.jpg",
      },
      {
        name: "Eba",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Eba",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2015/03/how-to-make-eba-food-nigerian-eba-img2-1.jpg",
      },
      {
        name: "FuFu",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful FuFu",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://kosherworldkitchen.com/wp-content/uploads/2024/12/Ghana-pounded-yam-fufu-scaled.jpg",
      },
      {
        name: "Meat",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Meat",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2020/02/boiled-meat-img-11-500x500.jpg",
      },
      {
        name: "Egg",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Egg",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://thumbs.dreamstime.com/b/hard-boiled-eggs-bowl-one-cut-25114925.jpg",
      },
      {
        name: "Fish",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Fish",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://static.vecteezy.com/system/resources/previews/050/392/528/non_2x/grilled-fish-with-lemon-and-herbs-on-white-background-photo.jpeg",
      },
      {
        name: "Plantain",
        price: 50,
        category: category[2],
        rating: 5,
        description: "One Tasteful Plan",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image:
          "https://flavortheglobe.com/wp-content/uploads/2021/12/Peruvian-oven-baked-plantains-recipe.jpg",
      },
      {
        name: "Pepsi",
        price: 350,
        category: category[0],
        rating: 4.3,
        description: "Chilled Pepsi drink",
        restaurantId: 4,
        isAvailable: "true",
        stock: 100,
        image: "https://m.media-amazon.com/images/I/51pGxfs4w1L.jpg",
      },

      //Blessed cafe 5
      {
        name: "White Rice with Stew",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of rice, stew ",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://img-global.cpcdn.com/recipes/b9a21d2844ba2ce2/1200x230cq20/photo.jpg",
      },
      {
        name: "Jollof Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Jollof Rice",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://allnigerianfoods.com/wp-content/uploads/jollof_rice_recipe1-500x500.jpg",
      },
      {
        name: "Fried Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Fried rice",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://nkechiajaeroh.com/wp-content/uploads/2020/12/Nigerian-fried-rice-recipe-main-photo-3.jpg",
      },
      {
        name: "Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "one spoon of Rice",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/02/23/0/FNK_Perfect-Long-Grain-White-Rice-H_s4x3.jpg.rend.hgtvcom.1280.920.suffix/1592939598228.webp",
      },
      {
        name: "Beans",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One spoon",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.ohmyveg.co.uk/wp-content/uploads/2024/10/masala-beans-2-220x540.jpg",
      },
      {
        name: "Spaghetti",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://stinkingood.com/wp-content/uploads/2022/01/iStock-128202421-scaled.jpg",
      },
      {
        name: "Indomie Noodles",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://sisijemimah.com/wp-content/uploads/2019/05/indomie-noodles-stir-fry-21-1024x238.jpg",
      },
      {
        name: "MoinMoin",
        price: 200,
        category: category[2],
        rating: 5,
        description: "One Tasteful Moi-Moi",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.seriouseats.com/thmb/FyrplS03gmSGkFlRtc5WuqMp5YY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230111-Moin-Moin-Maureen-Celestine-hero-5c252cbc3b284be1b1f29414f2bdc29c.JPG",
      },
      {
        name: "Amale",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Amale",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://yummieliciouz.com/wp-content/uploads/2023/04/easy-amala-recipe.jpg",
      },
      {
        name: "Eba",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Eba",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2015/03/how-to-make-eba-food-nigerian-eba-img2-1.jpg",
      },
      {
        name: "FuFu",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful FuFu",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://kosherworldkitchen.com/wp-content/uploads/2024/12/Ghana-pounded-yam-fufu-scaled.jpg",
      },
      {
        name: "Meat",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Meat",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2020/02/boiled-meat-img-11-500x500.jpg",
      },
      {
        name: "Egg",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Egg",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://thumbs.dreamstime.com/b/hard-boiled-eggs-bowl-one-cut-25114925.jpg",
      },
      {
        name: "Fish",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Fish",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://static.vecteezy.com/system/resources/previews/050/392/528/non_2x/grilled-fish-with-lemon-and-herbs-on-white-background-photo.jpeg",
      },
      {
        name: "Plantain",
        price: 50,
        category: category[2],
        rating: 5,
        description: "One Tasteful Plan",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image:
          "https://flavortheglobe.com/wp-content/uploads/2021/12/Peruvian-oven-baked-plantains-recipe.jpg",
      },
      {
        name: "Pepsi",
        price: 350,
        category: category[0],
        rating: 4.3,
        description: "Chilled Pepsi drink",
        restaurantId: 5,
        isAvailable: "true",
        stock: 100,
        image: "https://m.media-amazon.com/images/I/51pGxfs4w1L.jpg",
      },

      //BUWA Cafeteria beside law college 6
      {
        name: "White Rice with Stew",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of rice, stew ",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://img-global.cpcdn.com/recipes/b9a21d2844ba2ce2/1200x230cq20/photo.jpg",
      },
      {
        name: "Jollof Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Jollof Rice",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://allnigerianfoods.com/wp-content/uploads/jollof_rice_recipe1-500x500.jpg",
      },
      {
        name: "Fried Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Fried rice",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://nkechiajaeroh.com/wp-content/uploads/2020/12/Nigerian-fried-rice-recipe-main-photo-3.jpg",
      },
      {
        name: "Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "one spoon of Rice",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/02/23/0/FNK_Perfect-Long-Grain-White-Rice-H_s4x3.jpg.rend.hgtvcom.1280.920.suffix/1592939598228.webp",
      },
      {
        name: "Beans",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One spoon",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.ohmyveg.co.uk/wp-content/uploads/2024/10/masala-beans-2-220x540.jpg",
      },
      {
        name: "Spaghetti",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://stinkingood.com/wp-content/uploads/2022/01/iStock-128202421-scaled.jpg",
      },
      {
        name: "Indomie Noodles",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://sisijemimah.com/wp-content/uploads/2019/05/indomie-noodles-stir-fry-21-1024x238.jpg",
      },
      {
        name: "MoinMoin",
        price: 200,
        category: category[2],
        rating: 5,
        description: "One Tasteful Moi-Moi",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.seriouseats.com/thmb/FyrplS03gmSGkFlRtc5WuqMp5YY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230111-Moin-Moin-Maureen-Celestine-hero-5c252cbc3b284be1b1f29414f2bdc29c.JPG",
      },
      {
        name: "Amale",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Amale",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://yummieliciouz.com/wp-content/uploads/2023/04/easy-amala-recipe.jpg",
      },
      {
        name: "Eba",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Eba",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2015/03/how-to-make-eba-food-nigerian-eba-img2-1.jpg",
      },
      {
        name: "FuFu",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful FuFu",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://kosherworldkitchen.com/wp-content/uploads/2024/12/Ghana-pounded-yam-fufu-scaled.jpg",
      },
      {
        name: "Meat",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Meat",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2020/02/boiled-meat-img-11-500x500.jpg",
      },
      {
        name: "Egg",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Egg",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://thumbs.dreamstime.com/b/hard-boiled-eggs-bowl-one-cut-25114925.jpg",
      },
      {
        name: "Fish",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Fish",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://static.vecteezy.com/system/resources/previews/050/392/528/non_2x/grilled-fish-with-lemon-and-herbs-on-white-background-photo.jpeg",
      },
      {
        name: "Plantain",
        price: 50,
        category: category[2],
        rating: 5,
        description: "One Tasteful Plan",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://flavortheglobe.com/wp-content/uploads/2021/12/Peruvian-oven-baked-plantains-recipe.jpg",
      },
      {
        name: "Pepsi",
        price: 350,
        category: category[0],
        rating: 4.3,
        description: "Chilled Pepsi drink",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image: "https://m.media-amazon.com/images/I/51pGxfs4w1L.jpg",
      },

      //Jubileee 7
      {
        name: "White Rice with Stew",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of rice, stew ",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://img-global.cpcdn.com/recipes/b9a21d2844ba2ce2/1200x230cq20/photo.jpg",
      },
      {
        name: "Jollof Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Jollof Rice",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://allnigerianfoods.com/wp-content/uploads/jollof_rice_recipe1-500x500.jpg",
      },
      {
        name: "Fried Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Fried rice",
        restaurantId: 6,
        isAvailable: "true",
        stock: 100,
        image:
          "https://nkechiajaeroh.com/wp-content/uploads/2020/12/Nigerian-fried-rice-recipe-main-photo-3.jpg",
      },
      {
        name: "Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "one spoon of Rice",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/02/23/0/FNK_Perfect-Long-Grain-White-Rice-H_s4x3.jpg.rend.hgtvcom.1280.920.suffix/1592939598228.webp",
      },
      {
        name: "Beans",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One spoon",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.ohmyveg.co.uk/wp-content/uploads/2024/10/masala-beans-2-220x540.jpg",
      },
      {
        name: "Spaghetti",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://stinkingood.com/wp-content/uploads/2022/01/iStock-128202421-scaled.jpg",
      },
      {
        name: "Indomie Noodles",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://sisijemimah.com/wp-content/uploads/2019/05/indomie-noodles-stir-fry-21-1024x238.jpg",
      },
      {
        name: "MoinMoin",
        price: 200,
        category: category[2],
        rating: 5,
        description: "One Tasteful Moi-Moi",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.seriouseats.com/thmb/FyrplS03gmSGkFlRtc5WuqMp5YY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230111-Moin-Moin-Maureen-Celestine-hero-5c252cbc3b284be1b1f29414f2bdc29c.JPG",
      },
      {
        name: "Amale",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Amale",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://yummieliciouz.com/wp-content/uploads/2023/04/easy-amala-recipe.jpg",
      },
      {
        name: "Eba",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Eba",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2015/03/how-to-make-eba-food-nigerian-eba-img2-1.jpg",
      },
      {
        name: "FuFu",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful FuFu",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://kosherworldkitchen.com/wp-content/uploads/2024/12/Ghana-pounded-yam-fufu-scaled.jpg",
      },
      {
        name: "Meat",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Meat",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2020/02/boiled-meat-img-11-500x500.jpg",
      },
      {
        name: "Egg",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Egg",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://thumbs.dreamstime.com/b/hard-boiled-eggs-bowl-one-cut-25114925.jpg",
      },
      {
        name: "Fish",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Fish",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://static.vecteezy.com/system/resources/previews/050/392/528/non_2x/grilled-fish-with-lemon-and-herbs-on-white-background-photo.jpeg",
      },
      {
        name: "Plantain",
        price: 50,
        category: category[2],
        rating: 5,
        description: "One Tasteful Plan",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image:
          "https://flavortheglobe.com/wp-content/uploads/2021/12/Peruvian-oven-baked-plantains-recipe.jpg",
      },
      {
        name: "Pepsi",
        price: 350,
        category: category[0],
        rating: 4.3,
        description: "Chilled Pepsi drink",
        restaurantId: 7,
        isAvailable: "true",
        stock: 100,
        image: "https://m.media-amazon.com/images/I/51pGxfs4w1L.jpg",
      },

      //Destination Cafe  8
      {
        name: "White Rice with Stew",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of rice, stew ",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://img-global.cpcdn.com/recipes/b9a21d2844ba2ce2/1200x230cq20/photo.jpg",
      },
      {
        name: "Jollof Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Jollof Rice",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://allnigerianfoods.com/wp-content/uploads/jollof_rice_recipe1-500x500.jpg",
      },
      {
        name: "Fried Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One Spoon of Fried rice",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://nkechiajaeroh.com/wp-content/uploads/2020/12/Nigerian-fried-rice-recipe-main-photo-3.jpg",
      },
      {
        name: "Rice",
        price: 350,
        category: category[1],
        rating: 5,
        description: "one spoon of Rice",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2020/02/23/0/FNK_Perfect-Long-Grain-White-Rice-H_s4x3.jpg.rend.hgtvcom.1280.920.suffix/1592939598228.webp",
      },
      {
        name: "Beans",
        price: 350,
        category: category[1],
        rating: 5,
        description: "One spoon",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.ohmyveg.co.uk/wp-content/uploads/2024/10/masala-beans-2-220x540.jpg",
      },
      {
        name: "Spaghetti",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://stinkingood.com/wp-content/uploads/2022/01/iStock-128202421-scaled.jpg",
      },
      {
        name: "Indomie Noodles",
        price: 300,
        category: category[1],
        rating: 5,
        description: "One Spoon of Spaghetti",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://sisijemimah.com/wp-content/uploads/2019/05/indomie-noodles-stir-fry-21-1024x238.jpg",
      },
      {
        name: "MoinMoin",
        price: 200,
        category: category[2],
        rating: 5,
        description: "One Tasteful Moi-Moi",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.seriouseats.com/thmb/FyrplS03gmSGkFlRtc5WuqMp5YY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230111-Moin-Moin-Maureen-Celestine-hero-5c252cbc3b284be1b1f29414f2bdc29c.JPG",
      },
      {
        name: "Amale",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Amale",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://yummieliciouz.com/wp-content/uploads/2023/04/easy-amala-recipe.jpg",
      },
      {
        name: "Eba",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful Eba",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2015/03/how-to-make-eba-food-nigerian-eba-img2-1.jpg",
      },
      {
        name: "FuFu",
        price: 250,
        category: category[1],
        rating: 5,
        description: "One Tasteful FuFu",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://kosherworldkitchen.com/wp-content/uploads/2024/12/Ghana-pounded-yam-fufu-scaled.jpg",
      },
      {
        name: "Meat",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Meat",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.myactivekitchen.com/wp-content/uploads/2020/02/boiled-meat-img-11-500x500.jpg",
      },
      {
        name: "Egg",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Egg",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://thumbs.dreamstime.com/b/hard-boiled-eggs-bowl-one-cut-25114925.jpg",
      },
      {
        name: "Fish",
        price: 250,
        category: category[2],
        rating: 5,
        description: "One Tasteful Fish",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://static.vecteezy.com/system/resources/previews/050/392/528/non_2x/grilled-fish-with-lemon-and-herbs-on-white-background-photo.jpeg",
      },
      {
        name: "Plantain",
        price: 50,
        category: category[2],
        rating: 5,
        description: "One Tasteful Plan",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image:
          "https://flavortheglobe.com/wp-content/uploads/2021/12/Peruvian-oven-baked-plantains-recipe.jpg",
      },
      {
        name: "Pepsi",
        price: 350,
        category: category[0],
        rating: 4.3,
        description: "Chilled Pepsi drink",
        restaurantId: 8,
        isAvailable: "true",
        stock: 100,
        image: "https://m.media-amazon.com/images/I/51pGxfs4w1L.jpg",
      },

      //Forza cafe 1
      {
        name: "Stir fry spaghetti",
        price: 3000,
        category: category[1],
        rating: 4.3,
        description: "Stir fry spaghetti",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.fmnfoods.com/wp-content/uploads/2022/08/Veggie-Stir-Fry-Pasta.jpg",
      },
      {
        name: "Stir fry noodles",
        price: 2500,
        category: category[1],
        rating: 4.3,
        description: "Stir fry noodles",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://images.getrecipekit.com/20220724014720-rice-20noodles.png?aspect_ratio=4:3&quality=90&",
      },
      {
        name: "Jambalaya rice (fried/jellof)",
        price: 4000,
        category: category[1],
        rating: 4.3,
        description: "Jambalaya rice (fried/jellof)",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://bakesbychichi.com/wp-content/uploads/2020/06/DSC_1413-683x1024.jpg",
      },
      {
        name: "Yam",
        price: 100,
        category: category[1],
        rating: 4.3,
        description: "Yam",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://eatwellabi.com/wp-content/uploads/2021/09/Cooked-yam-on-a-plate-720x480.jpg",
      },
      {
        name: "Akara",
        price: 100,
        category: category[1],
        rating: 4.3,
        description: "Akara",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://cdn.apartmenttherapy.info/image/upload/v1634332056/k/Photo/Recipes/2021-10-akara-reshoot/2021-10-12_ATK8157.jpg",
      },
      {
        name: "Ofada rice ",
        price: 3000,
        category: category[1],
        rating: 4.3,
        description: "Ofada rice ",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://humblesagefood.com/wp-content/uploads/Ofada-and-Ayamase-sauce.jpg",
      },
      {
        name: "Pancake",
        price: 4500,
        category: category[1],
        rating: 4.3,
        description: "Pancake",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://static01.nyt.com/images/2021/02/22/dining/24COOKING-CLASSICPANCAKES-copy2/24COOKING-CLASSICPANCAKES-square640.jpg",
      },
      {
        name: "White rice",
        price: 350,
        category: category[1],
        rating: 4.3,
        description: "White rice",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://assets.epicurious.com/photos/57d70c8ade27564257b657c6/master/pass/perfect-steamed-rice.jpg",
      },
      {
        name: "Beans",
        price: 350,
        category: category[1],
        rating: 4.3,
        description: "Beans",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPSWljeDEcmyjiZEJWu0rD70uFisvCN4mQuw&s",
      },
      {
        name: "White spaghetti",
        price: 350,
        category: category[1],
        rating: 4.3,
        description: "White spaghetti",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://media.istockphoto.com/id/153817031/photo/cooked-spaghetti.jpg?s=612x612&w=0&k=20&c=NAc7YXsk1FHiaoujNoKiINyII2Z__h6i64UqptY-3K4=",
      },
      {
        name: "Beef meat",
        price: 250,
        category: category[1],
        rating: 4.3,
        description: "Beef meat",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://img.freepik.com/free-photo/stew-beef-pieces-beef-stewed-soy-sauce-with-spices-with-pickled-cucumber-asian-style_2829-20279.jpg?semt=ais_hybrid&w=740",
      },
      {
        name: "Boiled eggs",
        price: 300,
        category: category[1],
        rating: 4.3,
        description: "Boiled eggs",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://healthyrecipesblogs.com/wp-content/uploads/2024/07/hard-boiled-eggs-featured-1-2024.jpg",
      },
      {
        name: "Plantain",
        price: 100,
        category: category[1],
        rating: 4.3,
        description: "Plantain",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.allrecipes.com/thmb/dE6B-lRFVopvyMkQ8Gokb_2Jgfg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/146246-sauteed-sweet-plantains-ddfsm-3X4-5829-a0ea8438139444d68577f36bd0e9a773.jpg",
      },
      {
        name: "Jellof rice",
        price: 350,
        category: category[1],
        rating: 4.3,
        description: "Jellof rice",
        restaurantId: 1,
        isAvailable: "true",
        stock: 100,
        image:
          "https://www.simplyrecipes.com/thmb/-paU2Zi1V6rpSWmh8bta9Ajd2WE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Jollof-Rice-LEAD-6-5a93db14a0ac461f88dc557514a770c0.jpg",
      },
    ];

    await Product.bulkCreate(dataSet);
    console.log("✅ Products seeded successfully!");
  } catch (error) {
    console.error("❌ Error seeding products:", error);
  } finally {
    await sequelize.close();
  }
};

module.exports = seedProducts;
